### ISSUE TITLE
put back live_vs_dead results

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#55]
@ValentineHerr, 
During cleanup of this repository, we deleted results for live vs dead trees. Could you please put those back in this repository ASAP? We say this in the manuscript:

Chronologies of trees cored live and dead were pooled following analyses showing similar climate sensitivity up to 2009 for all four species with ≥10 cores in each category (LITU, QURU, QUVE, FRAM; comparison plots available at https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/tree/master/results/live_vs_dead).

**Comment by ValentineHerr** [comment]
The link works, can you specify what is missing ?
(FYI there is a big and long power outage here)

**Comment by teixeirak** [comment]
The full path no longer works. It redirects to the results folder, but live_vs_dead folder has been deleted.

**Comment by teixeirak** [comment]
Ack, I'm sorry. This is fine. Never mind.
