### ISSUE TITLE
incorporate new ANPP calculations

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#57]
Once [this issue](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/issues/10) is taken care of, we need to update ANPP numbers in the manuscript and tables.

**Comment by ValentineHerr** [comment]
FYI: I am waiting on Erika to tell me where the corrected allometies are.

**Comment by teixeirak** [comment]
One small change to how we calculate linear slopes: I realized that when we calculate the response [here](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/blob/f5dd613050d18ea6febd629a20efd36fdd551320/scripts/0-My_dplR_functions.R#L99), we should be using the sd.clim of only the time period of the current analysis in the ratio, versus the long-term mean to predict response to +1SD:

current: 
dc$chg_rad_inc_1SD_clim <- dc$coef * (sd.chrono / sd.clim) * sd.clim

change to:
dc$chg_rad_inc_1SD_clim <- dc$coef * (sd.chrono / sd.clim_analysis time frame) * sd.clim_full time frame

**Comment by ValentineHerr** [comment]
I made the update with new calculations.

**Comment by teixeirak** [comment]
THanks so much!
