### ISSUE TITLE
create new figure: time series for each species

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#59]
Let's plot the time series (line plot) of each species chronology from 1901-2009, starting each in the year when SSS≥0.75. Color code by species. Make this to be much wider than it is tall to show as much of the year-to-year variation as possible.

We may add an additional panel with a few climate variables, but let's first see how this looks.

**Comment by ValentineHerr** [comment]
If that is ok I am going to try to make one small and very flat panel per species because it is bit too crowded:
![image](https://user-images.githubusercontent.com/19673377/55037692-f73b8b80-4ff4-11e9-93db-1eaaac894cca.png)

**Comment by teixeirak** [comment]
Cool! They show a very consistent signal. Here's the reviewer comment:

"Show the actual time series of your 14 species, from which it becomes apparent how similar or different their inter-annual variability is (in terms of coefficient of variation, or, as you have it in the supplementary table, the mean sensitivity); and to get an impression how similar their inter-annual signal is in general, i.e. how well they correlate with each other."

This shows the correlation nicely, but it's hard to get a sense of the variability by species. Let's try your suggestion of separate panels and see how that looks.

**Comment by ValentineHerr** [comment]
This is what I have so far, maybe vertical lines across the plots would help see what you are talking about.
I'll try.

![image](https://user-images.githubusercontent.com/19673377/55038350-eb50c900-4ff6-11e9-83bf-5d5efa5afded.png)

**Comment by ValentineHerr** [comment]
I updated comment above with vertical lines

**Comment by teixeirak** [comment]
I like it!

**Comment by teixeirak** [comment]
Let's re-order by contributions to productivity (same as current Fig.1).

**Comment by teixeirak** [comment]
Do you think it would work to put a few key climate variables in a panel above? Perhaps mean May-July PET, PRE, and PET-PRE ?

**Comment by ValentineHerr** [comment]
I can try.
On panel per variable and one line per month?

**Comment by ValentineHerr** [comment]
Never mind I just saw the "mean"

**Comment by teixeirak** [comment]
Just mean for those months. PET and PRE should fit on the same scale if you use PETsum. Actually, if you do that, no need to show their difference.

**Comment by ValentineHerr** [comment]
I ended up putting them on 2 different panel because petsum has a smaller range and it looked almost flat.
Still needs some adjustments but here is what it looks like:

![image](https://user-images.githubusercontent.com/19673377/55044825-244a6700-5012-11e9-9dde-105fc5ae1216.png)

also [here](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/blob/master/results/Time_series_for_each_species.tif)

**Comment by teixeirak** [comment]
Looks good! Let’s put PRE after PET because the tree rings move in the same direction as PRE and it will make the correlation a bit easier to follow.

**Comment by teixeirak** [comment]
Also, we need to add a proper y-axis label. Could you please check the documentation to make sure we get the terminology right?

**Comment by ValentineHerr** [comment]
I believe I can replace "res" by "RWI" for "Ring Width Index" but maybe @tepleya can confirm.
Noe the plot looks like this:
![image](https://user-images.githubusercontent.com/19673377/55236458-58867900-5206-11e9-9985-bd69274d7588.png)

Let me know if that works for you think.
Maybe I should remove the bold line for PRE ?

**Comment by teixeirak** [comment]
Let's make PET bold red and PRE bold blue, as that will make this slightly more intuitive. (Actually, there's no need to have different line types for any of the series, but I like how it looks.)

I think that it would look best to just put the units of the climate variables (mm mo-1) on the y-axis, and then put the labels on the right side where they were. Please label PETsum just "PET". Let's also spell out RWI (or whatever we end up putting there.).

**Comment by ValentineHerr** [comment]
updated figure:
![image](https://user-images.githubusercontent.com/19673377/55240393-32b1a200-520f-11e9-8ef2-eb1939329246.png)

**Comment by teixeirak** [comment]
Neil suggests:  instead of highlighting the decades, maybe highlight the most severe X number of droughts/drought stress with translucent bars to indicate how each species responded.

This is lower priority, though. The figure is fine as as.

**Comment by ValentineHerr** [comment]
That would be easy.
Do you have dates handy?

**Comment by teixeirak** [comment]
No, the tricky part would be determining what those should be. Droughts can be complex/ take different forms. Why don't we try the 10 largest PET-PRE (based on the 3-mo average values plotted here)?

**Comment by ValentineHerr** [comment]
10 largest PET-PRE: 112.43, 89.43, 86.97, 84.57, 83.87, 83.37, 82.63, 82.13, 81.9, 
80
Corresponding drought years: 1911, 1914, 1930, 1936, 1944, 1964, 1966, 1977, 1999, 2007





![image](https://user-images.githubusercontent.com/19673377/55258562-94870180-5239-11e9-8b97-c0433812607e.png)

**Comment by teixeirak** [comment]
Wow, do they really go in chronological order like that? 
Anyway, the plot looks good.

**Comment by ValentineHerr** [comment]
Good point, they don't, my mistake.
I updated the comment above.

**Comment by teixeirak** [comment]
Thanks! This is done, unless we end up needing to change the y-axis.

**Comment by teixeirak** [comment]
@ValentineHerr, Alan commented that it would be good to make FRAM a little darker on this figure, and I agree,  but its not essential; I'll go ahead with submission regardless of whether you're able to get that done.

**Comment by ValentineHerr** [comment]
Ok I updated the figure and pushed.

it now looks like this:

![image](https://user-images.githubusercontent.com/19673377/56591320-861cd300-65b6-11e9-876f-8ab5e6384250.png)

**Comment by teixeirak** [comment]
Thanks! Nice colors!
