### ISSUE TITLE
produce figures showing ∆ANPP by species

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#61]
Let's prepare figures like current figure 2 for each species. On the colorbar, include both absolute change (Mg ha-1 yr-1) and % change (relative to that species' ANPP)-- they will scale linearly. Also, add % change to the all-species colorbar.

**Comment by teixeirak** [comment]
Modification: rather than sorting by species, sort by climate variable. Tentatively, I'd like to replace the second panel in previous Fig. 1 with ∆ANPP (by species) for the full time period.

**Comment by teixeirak** [comment]
Back to this, I'm now not sure which of the arrangements described above we'll want to show. I'd like to see how the results look before deciding. Please make draft plots in whichever arrangement is easiest (saving the matrix of underlying values), and we will go from there.

**Comment by ValentineHerr** [comment]
@teixeirak, I think I am a bit confused with this and might wait until we can talk in person.

**Comment by ValentineHerr** [comment]
@teixeirak, is this what you were thinking ?
![image](https://user-images.githubusercontent.com/19673377/55416049-204fa500-553c-11e9-9f17-ac1c0598f50b.png)

**Comment by ValentineHerr** [comment]
Newest figure looks like this:
![image](https://user-images.githubusercontent.com/19673377/55569843-460db300-56d0-11e9-9b3c-2becee71e10a.png)

**Comment by teixeirak** [comment]
Looks great in general! Could you please make a few minor changes?:
- could you please put the max value back to +0.65 on this one?
- Scale on % response needs to be multiplied by 100.
- Add label on i): ANPP (Mg ha-1 yr-1)

**Comment by ValentineHerr** [comment]
Oh yes, thanks for catching that, I forgot to update the legend.
I pushed the fixed version.
