### ISSUE TITLE
output SD for each species chronology

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#63]
@ValentineHerr, we'll want to add the SD for each species chronology (full analysis time frame) to table S1. Could you please output those?

**Comment by ValentineHerr** [comment]
I am not sure I know what SD you are talking about.
I believe @RHelcoski created table S1 and I am not familiar with how he did it.

**Comment by teixeirak** [comment]
The SD would just be calculated on the chronology residuals that you plot in the new figure.
Don't worry about putting it in the table.

**Comment by ValentineHerr** [comment]
Species | SD
-- | --
CACO | 0.13
CAGL | 0.11
CAOVL | 0.11
CATO | 0.18
FAGR | 0.15
FRAM | 0.1
FRNI | 0.15
JUNI | 0.18
LITU | 0.14
PIST | 0.16
QUAL | 0.12
QUPR | 0.14
QURU | 0.1
QUVE | 0.13

result also [here](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/blob/master/results/SD_of_each_detrended_chornologies.csv)

**Comment by teixeirak** [comment]
Thanks!
