### ISSUE TITLE
produce matrix of correlations among species' chronologies 

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#64]
@ValentineHerr, one more thing I forgot to add--
Could you please create a matrix of the correlations between species chronologies? This will be a supplementary table (plus discussed in the results).

**Comment by ValentineHerr** [comment]
Would you like a figure like this instead ?
It represents the coefficients of correlation, blue when positive, red when negative, the size of the numbers are proportional to the correlation (very tiny ones are close to zero)

![image](https://user-images.githubusercontent.com/19673377/55237438-908ebb80-5208-11e9-93b2-5e133e6d677e.png)

**Comment by teixeirak** [comment]
Sorry for the slow response, GitHub notifications keep getting caught in my junk folder (arggghh!). 

This is wonderful! The one thing is that the tiny numbers are of course impossible to read. Perhaps shade the boxes instead?

**Comment by teixeirak** [comment]
(but don't bother if that would take a long time. This will be a SI figure.)

**Comment by ValentineHerr** [comment]
I adjusted the code to not make tiny numbers:

![image](https://user-images.githubusercontent.com/19673377/55252598-b24c6a80-5229-11e9-8712-543adaa04b40.png)

**Comment by teixeirak** [comment]
Perfect!

**Comment by teixeirak** [comment]
Oh, could you please provide the average of all (for results section)?

**Comment by ValentineHerr** [comment]
0.41
