### ISSUE TITLE
Plan & prepare figures/tables with new time periods

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#65]
Assuming results in issue #60 do not change when we run the adjusted time periods, we will  want to update tables/figures to present results from the 3 33-year time periods, in addition to the full 110 years.

- [x] I need to plan how these will be arranged/ what we will highlight in the main text. 
- [x] @ValentineHerr, could you please modify the climate figure [here](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/tree/master/results/climate) to show the 4 different time periods? Hopefully that won't be too busy. Perhaps use red,blue,yellow for the 3 time periods + bold black for the mean.
- [x] We will want to update the supplementary tables and figures to include all four time periods: first the full one, then the 3 33-year periods. For the figures ([here](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/tree/master/results/figures_for_manuscript/supplementary_figures)), we can do 4 panel (2x2) figures for each variable. For the tables ([here](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/blob/master/results/tables_for_manuscript/Supplementary_tables_Pearson_correlation_summary_per_variable.docx)), I'm not sure how to make it fit. Probably separate into 2 or 4 small tables, which we can group together in the SI.

**Comment by ValentineHerr** [comment]
@teixeirak, 
I updated the tables and figures.
Let me know what you think.
Note that for the supp tables, I used a landscape orientation and narrow margins and smaller font.

**Comment by teixeirak** [comment]
These look great; thanks!

**Comment by teixeirak** [comment]
I'm having trouble with the tables (trying to fit to vertical orientation because I've had trouble with landscape orientation in SI materials in the past). Could you please change the "n significant" and "n positive" columns to "n sig" and "n pos", and drop the 3 decimal places?  Then I should be able to fit it with reasonable font size.

**Comment by ValentineHerr** [comment]
I updated the word document with portrait orientation

**Comment by teixeirak** [comment]
Something went wrong there-- month names were replaced by numbers.

**Comment by ValentineHerr** [comment]
I fixed that.
Running for 3 different time periods now.

**Comment by teixeirak** [comment]
Please stick with the most recent set of time periods: 1920-49, 1950-79, and 1980-2009.

**Comment by teixeirak** [comment]
For Fig. 4, let's do a comparison of ANPP in the 3 time periods, formatted like Fig. 3. Draft below.
<img width="784" alt="Screen Shot 2019-04-06 at 8 34 52 AM" src="https://user-images.githubusercontent.com/6355854/55669569-f00f4b80-5846-11e9-8404-44358329f195.png">

**Comment by teixeirak** [comment]
- [ ] Also, please remove the variable labels in the upper left corners on the SI figures. They are not needed, and PDSI_prewhiten label covers up part of the legend

**Comment by ValentineHerr** [comment]
I pushed the new figures. Let me know if they work.

**Comment by teixeirak** [comment]
Looks great; thanks!
