### ISSUE TITLE
save matrices of % response

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#66]
@ValentineHerr, please have the code to save matrices of % response. Those will be useful for other projects (canopy position, traits).

**Comment by ValentineHerr** [comment]
Isn't [this ](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/blob/master/results/1901_2009/tables/monthly_responses_ANPP_to_climate_variables/ANPP_response_by_species_climate_variable_and_month.csv) what you want ?

**Comment by teixeirak** [comment]
Yes, that works!
