### ISSUE TITLE
re-run scripts for dead_vs_live and canopy_vs_subcanopy to get % response (non-urgent)

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/climate_sensitivity_cores#67]
I am considering removing results related to livs_vs_dead and canopy_vs_subcanopy, is that all right? I'll leave the scripts that can be reused to re-generate them (although, I have not been maintaining those scripts with recent changes of time periods etc...)

**Comment by teixeirak** [comment]
I'd kind of like to save them for now. I'm not aware of anything wrong with them, are you? The only scientifically meaningful change we made was the ANPP calculation, but ANPP calculations were never part of that analysis. The % response will be a better variable to use in the analyses that @mcgregorian1 has tried, but the correlation values are not inherently wrong.

I'll change the title of this issue to remind us that those scripts can/should be re-run when/if we want % response values.

**Comment by teixeirak** [comment]
Outdated; closing this.
