### ISSUE TITLE
create higher quality versions of Figs. 1-2

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#68]
@ValentineHerr, I just got an email from New Phytologist asking for better quality versions of Figs. 1 & 2. They are fairly grainy when you zoom in. Could you please make higher-res versions as soon as you have a chance?

**Comment by ValentineHerr** [comment]
I updated the figures in GitHub and Dropbox (Smithsonian)\climate sensitivity\MANUSCRIPT\2019_5_2_NewPhyt final

**Comment by teixeirak** [comment]
Thanks! I I see them in Dropbox, but I think you forgot to push to GitHub.

**Comment by ValentineHerr** [comment]
indeed. fixed now.
